const periodicTable = [
    {groups:'1. Alkalimetallit',
        id:1,
        description:'Alkalimetallit ovat ryhmän 1 alkuaineita, jotka ovat erittäin reaktiivisia ja pehmeitä metalleja (paitsi vety). Ne reagoivat voimakkaasti veden kanssa muodostaen emäksisiä liuoksia ja vetykaasua. Alkalimetallit ovat myös hyviä sähkön- ja lämmönjohteita.'
     ,
     elements: [
        {AtomicNumber: 1, 
            Symbol: 'H',
             Name: 'Vety', 
             AtomicMass: 1.008,
             OuterElectronConfiguration: '1s1',
             ElementofLive:'Yksi elämän kannalta tärkeinpiä alkuaineita veden ja orgaanisten yhdisteiden rakennusaineena. Vety on myös tärkeä polttoaine, jota voidaan käyttää energianlähteenä.'},
        {AtomicNumber: 3, 
            Symbol: 'Li',
             Name: 'Litium', 
             AtomicMass: 6.94,
             OuterElectronConfiguration: '2s1',
             ElementofLive:'Myrkyllinen, mutta sitä käytetään mm. akkujen valmistuksessa ja lääkkeissä.'},
        {AtomicNumber: 11, 
            Symbol: 'Na',
             Name: 'Natrium', 
             AtomicMass: 22.99,
             OuterElectronConfiguration: '3s1',
             ElementofLive:'Tärkeä elektrolyytti elimistössä, jota tarvitaan mm. hermoston ja lihasten toimintaan.'},
        {AtomicNumber: 19, 
            Symbol: 'K',
             Name: 'Kalium', 
             AtomicMass: 39.10,
             OuterElectronConfiguration: '4s1',
             ElementofLive:'Tärkeä elektrolyytti elimistössä, rikastuu solun sisällä, jota tarvitaan mm. hermoston ja lihasten toimintaan.'},
{AtomicNumber: 37, 
            Symbol: 'Rb',
             Name: 'Rubidium', 
             AtomicMass: 85.47,
             OuterElectronConfiguration: '5s1',
             ElementofLive:''},
        {AtomicNumber: 55, 
            Symbol: 'Cs',
             Name: 'Cesium', 
             AtomicMass: 132.91,
             OuterElectronConfiguration: '6s1',
             ElementofLive:''},
        {AtomicNumber: 87, 
            Symbol: 'Fr',
             Name: 'Francium', 
             AtomicMass: 223,
             OuterElectronConfiguration: '7s1',
             ElementofLive:''}
    ]
    },
    {groups:'2. Maa-alkalimetallit',
        id:2,
        description: '',  
    elements: [
        
        {AtomicNumber: 4, 
            Symbol: 'Be',
             Name: 'Berillium', 
             AtomicMass: 9.01,
             OuterElectronConfiguration: '2s2   ',
             ElementofLive:''},
        {AtomicNumber: 12, 
            Symbol: 'Mg',
             Name: 'Magnesium', 
             AtomicMass: 24.31,
             OuterElectronConfiguration: '3s2   ',
             ElementofLive:''},
             
        {AtomicNumber: 20, 
            Symbol: 'Ca',
             Name: 'Kalsium', 
             AtomicMass: 40.08,
             OuterElectronConfiguration: '4s2   ',
             ElementofLive:''},
        {AtomicNumber: 38, 
            Symbol: 'Sr',
             Name: 'Strontium', 
             AtomicMass: 87.62,
             OuterElectronConfiguration: '5s2   ',
             ElementofLive:''},
        {AtomicNumber: 56, 
            Symbol: 'Ba',
             Name: 'Barium', 
             AtomicMass: 137.33,
             OuterElectronConfiguration: '6s2   ',
             ElementofLive:''},
        {AtomicNumber: 88, 
            Symbol: 'Ra',
             Name: 'Radium', 
             AtomicMass: 226,
             OuterElectronConfiguration: '7s2   ',
             ElementofLive:''}
        
       
            ]}
    

    ]